#goal definition
string target_landmark
string direction_landmark
string human

---
#result definition
geometry_msgs/PoseStamped robot_pose
geometry_msgs/PoseStamped human_pose
string[] pointed_landmarks

---
#feedback
int8 START=0
int8 START_PLANNING=1
int8 SUCCESS=2
int8 NO_SOLUTION=-1
int8 FAILURE=-2
int8 state

