# This is the service definition to start a fact
# The description of the fact need to be in the following format :
# "<predicate>(<subject_name>,<object_name>)" for n2 predicates
# "<predicate>(<subject_name>)" for n1 predicates
string world_name # the underworlds world where start the fact
string description # the predicate
int64 starttime # the starting time of the fact, if zero, the fact is stamped when the service receive the request
bool is_event # if true the fact is an event : start_time = end_time
---
string fact_id # the ID generated (save it to be able to end the fact)
bool success